export default { normalize: '/*! normalize.css v7.0.0 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,footer,header,nav,section{display:block}h1{font-size:2em;margin:.67em 0}figcaption,figure,main{display:block}figure{margin:1em 40px}hr{box-sizing:content-box;height:0;overflow:visible}pre{font-family:monospace,monospace;font-size:1em}a{background-color:transparent;-webkit-text-decoration-skip:objects}abbr[title]{border-bottom:none;text-decoration:underline;text-decoration:underline dotted}b,strong{font-weight:inherit;font-weight:bolder}code,kbd,samp{font-family:monospace,monospace;font-size:1em}dfn{font-style:italic}mark{background-color:#ff0;color:#000}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sub{bottom:-.25em}sup{top:-.5em}audio,video{display:inline-block}audio:not([controls]){display:none;height:0}img{border-style:none}svg:not(:root){overflow:hidden}button,input,optgroup,select,textarea{font-family:sans-serif;font-size:100%;line-height:1.15;margin:0}button,input{overflow:visible}button,select{text-transform:none}/* 1 */ [type=reset],[type=submit],button,html [type=button]{-webkit-appearance:button}[type=button]::-moz-focus-inner,[type=reset]::-moz-focus-inner,[type=submit]::-moz-focus-inner,button::-moz-focus-inner{border-style:none;padding:0}[type=button]:-moz-focusring,[type=reset]:-moz-focusring,[type=submit]:-moz-focusring,button:-moz-focusring{outline:1px dotted ButtonText}fieldset{padding:.35em .75em .625em}legend{box-sizing:border-box;color:inherit;display:table;max-width:100%;padding:0;white-space:normal}progress{display:inline-block;vertical-align:baseline}textarea{overflow:auto}[type=checkbox],[type=radio]{box-sizing:border-box;padding:0}[type=number]::-webkit-inner-spin-button,[type=number]::-webkit-outer-spin-button{height:auto}[type=search]{-webkit-appearance:textfield;outline-offset:-2px}[type=search]::-webkit-search-cancel-button,[type=search]::-webkit-search-decoration{-webkit-appearance:none}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}/* 1 */ menu,details{display:block}summary{display:list-item}canvas{display:inline-block}[hidden],template{display:none}a,article,body,code,dd,div,dl,dt,fieldset,footer,form,h1,h2,h3,h4,h5,h6,header,html,input[type=email],input[type=number],input[type=password],input[type=tel],input[type=text],input[type=url],legend,li,main,ol,p,pre,section,table,td,textarea,th,tr,ul{box-sizing:border-box}',
  html: 'box-sizing: border-box;',
  body: 'min-height: 100vh;margin: 0;background: #232c3b;color: #63768d;font-family: -apple-system, BlinkMacSystemFont, \'avenir next\', avenir, \'helvetica neue\', helvetica, ubuntu, roboto, noto, \'segoe ui\', arial, sans-serif;',
  articleAsideFooterHeaderNavSection: 'display: block;',
  h1: 'height: 1rem;',
  figcaptionFigureMain: 'display: block;',
  figure: 'margin: 1em 40px;',
  hr: 'box-sizing: content-box;height: 0;overflow: visible;',
  pre: 'white-space: pre;',
  a: 'color: #4786ff;',
  abbrTitle: 'border-bottom: none;text-decoration: underline;text-decoration: underline dotted;',
  bStrong: 'font-weight: bolder;',
  codeKbdSamp: 'font-family: monospace, monospace;font-size: 1em;',
  dfn: 'font-style: italic;',
  mark: 'background-color: #ff0;color: #000;',
  small: 'font-size: 80%;',
  subSup: 'font-size: 75%;line-height: 0;position: relative;vertical-align: baseline;',
  sub: 'bottom: -0.25em;',
  sup: 'top: -0.5em;',
  audioVideo: 'display: inline-block;',
  audioNotControls: 'display: none;height: 0;',
  img: 'max-width: 100%;',
  svgNotRoot: 'overflow: hidden;',
  buttonInputOptgroupSelectTextarea: 'font-family: sans-serif;font-size: 100%;line-height: 1.15;margin: 0;',
  buttonInput: 'overflow: visible;',
  buttonSelect: 'text-transform: none;',
  buttonHtmlTypeButtonTypeResetTypeSubmit: '-webkit-appearance: button;',
  buttonMozFocusInnerTypeButtonMozFocusInnerTypeResetMozFocusInnerTypeSubmitMozFocusInner: 'border-style: none;padding: 0;',
  buttonMozFocusringTypeButtonMozFocusringTypeResetMozFocusringTypeSubmitMozFocusring: 'outline: 1px dotted ButtonText;',
  fieldset: 'border: 1px solid #c0c0c0;margin: 0 2px;padding: .35em .625em .75em;',
  legend: 'box-sizing: border-box;color: inherit;display: table;max-width: 100%;padding: 0;white-space: normal;',
  progress: 'display: inline-block;vertical-align: baseline;',
  textarea: 'overflow: auto;',
  typeCheckboxTypeRadio: 'box-sizing: border-box;padding: 0;',
  typeNumberWebkitInnerSpinButtonTypeNumberWebkitOuterSpinButton: 'height: auto;',
  typeSearch: '-webkit-appearance: textfield;outline-offset: -2px;',
  typeSearchWebkitSearchCancelButtonTypeSearchWebkitSearchDecoration: '-webkit-appearance: none;',
  webkitFileUploadButton: '-webkit-appearance: button;font: inherit;',
  detailsMenu: 'display: block;',
  summary: 'display: list-item;',
  canvas: 'display: inline-block;',
  template: 'display: none;',
  hidden: 'display: none;',
  aspectRatio: 'height: 0;position: relative;',
  aspectRatio16X9: 'padding-bottom: 56.25%;',
  aspectRatio9X16: 'padding-bottom: 177.77%;',
  aspectRatio4X3: 'padding-bottom: 75%;',
  aspectRatio3X4: 'padding-bottom: 133.33%;',
  aspectRatio6X4: 'padding-bottom: 66.6%;',
  aspectRatio4X6: 'padding-bottom: 150%;',
  aspectRatio8X5: 'padding-bottom: 62.5%;',
  aspectRatio5X8: 'padding-bottom: 160%;',
  aspectRatio7X5: 'padding-bottom: 71.42%;',
  aspectRatio5X7: 'padding-bottom: 140%;',
  aspectRatio1X1: 'padding-bottom: 100%;',
  aspectRatioObject: 'position: absolute;top: 0;right: 0;bottom: 0;left: 0;width: 100%;height: 100%;z-index: 100;',
  bgCenter: 'background-repeat: no-repeat;background-position: center center;',
  bgTop: 'background-repeat: no-repeat;background-position: top center;',
  bgRight: 'background-repeat: no-repeat;background-position: center right;',
  bgBottom: 'background-repeat: no-repeat;background-position: bottom center;',
  bgLeft: 'background-repeat: no-repeat;background-position: center left;',
  cover: 'background-size: cover;',
  contain: 'background-size: contain;',
  htmlBody: 'height: 100%;',
  beforeAfter: 'box-sizing: inherit;',
  code: 'color: #59cd90;',
  br0: 'border-right-width: 0;',
  br1: 'border-radius: .125rem;',
  br2: 'border-radius: .25rem;',
  br3: 'border-radius: .5rem;',
  br4: 'border-radius: 1rem;',
  br100: 'border-radius: 100%;',
  brPill: 'border-radius: 9999px;',
  brBottom: 'border-top-left-radius: 0;border-top-right-radius: 0;',
  brTop: 'border-bottom-left-radius: 0;border-bottom-right-radius: 0;',
  brRight: 'border-top-left-radius: 0;border-bottom-left-radius: 0;',
  brLeft: 'border-top-right-radius: 0;border-bottom-right-radius: 0;',
  bDotted: 'border-style: dotted;',
  bDashed: 'border-style: dashed;',
  bSolid: 'border-style: solid;',
  bNone: 'border-style: none;',
  bw0: 'border-width: 0;',
  bw1: 'border-width: .125rem;',
  bw2: 'border-width: .25rem;',
  bw3: 'border-width: .5rem;',
  bw4: 'border-width: 1rem;',
  bw5: 'border-width: 2rem;',
  bt0: 'border-top-width: 0;',
  bb0: 'border-bottom-width: 0;',
  bl0: 'border-left-width: 0;',
  ba: 'border-style: solid;border-width: 1px;',
  bt: 'border-top-style: solid;border-top-width: 1px;',
  br: 'border-right-style: solid;border-right-width: 1px;',
  bb: 'border-bottom-style: solid;border-bottom-width: 1px;',
  bl: 'border-left-style: solid;border-left-width: 1px;',
  bn: 'border-style: none;border-width: 0;',
  htmlBodyDivArticleSectionMainFooterHeaderFormFieldsetLegendPreCodePAH1H2H3H4H5H6UlOlLiDlDtDdTextareaInputTypeEmailInputTypeNumberInputTypePasswordInputTypeTelInputTypeTextInputTypeUrlBorderBox: 'box-sizing: border-box;',
  cfBeforeCfAfter: 'content: " ";display: table;',
  cfAfter: 'clear: both;',
  cf: 'zoom: 1;',
  cl: 'clear: left;',
  cr: 'clear: right;',
  cb: 'clear: both;',
  cn: 'clear: none;',
  top0: 'top: 0;',
  right0: 'right: 0;',
  bottom0: 'bottom: 0;',
  left0: 'left: 0;',
  top1: 'top: -1rem;',
  right1: 'right: -1rem;',
  bottom1: 'bottom: -1rem;',
  left1: 'left: -1rem;',
  top2: 'top: -2rem;',
  right2: 'right: -2rem;',
  bottom2: 'bottom: -2rem;',
  left2: 'left: -2rem;',
  absoluteFill: 'top: 0;right: 0;bottom: 0;left: 0;',
  dn: 'display: none;',
  di: 'display: inline;',
  db: 'display: block;',
  dib: 'display: inline-block;',
  dit: 'display: inline-table;',
  dt: 'display: table;',
  dtc: 'display: table-cell;',
  dtRow: 'display: table-row;',
  dtRowGroup: 'display: table-row-group;',
  dtColumn: 'display: table-column;',
  dtColumnGroup: 'display: table-column-group;',
  dtFixed: 'table-layout: fixed;width: 100%;',
  fl: 'float: left;display: inline;',
  fr: 'float: right;display: inline;',
  fn: 'float: none;',
  sansSerif: 'font-family: -apple-system, BlinkMacSystemFont, \'avenir next\', avenir, helvetica, \'helvetica neue\', ubuntu, roboto, noto, \'segoe ui\', arial, sans-serif;',
  serif: 'font-family: georgia, times, serif;',
  systemSansSerif: 'font-family: sans-serif;',
  systemSerif: 'font-family: serif;',
  codeCode: 'font-family: Consolas, monaco, monospace;',
  courier: 'font-family: \'Courier Next\', courier, monospace;',
  helvetica: 'font-family: \'helvetica neue\', helvetica, sans-serif;',
  avenir: 'font-family: \'avenir next\', avenir, sans-serif;',
  athelas: 'font-family: athelas, georgia, serif;',
  georgia: 'font-family: georgia, serif;',
  times: 'font-family: times, serif;',
  bodoni: 'font-family: "Bodoni MT", serif;',
  calisto: 'font-family: "Calisto MT", serif;',
  garamond: 'font-family: garamond, serif;',
  baskerville: 'font-family: baskerville, serif;',
  i: 'font-style: italic;',
  fsNormal: 'font-style: normal;',
  normal: 'font-weight: normal;',
  b: 'font-weight: bold;',
  fw1: 'font-weight: 100;',
  fw2: 'font-weight: 200;',
  fw3: 'font-weight: 300;',
  fw4: 'font-weight: 400;',
  fw5: 'font-weight: 500;',
  fw6: 'font-weight: 600;',
  fw7: 'font-weight: 700;',
  fw8: 'font-weight: 800;',
  fw9: 'font-weight: 900;',
  inputReset: '-webkit-appearance: none;-moz-appearance: none;',
  buttonResetMozFocusInnerInputResetMozFocusInner: 'border: 0;padding: 0;',
  h2: 'height: 2rem;',
  h3: 'height: 4rem;',
  h4: 'height: 8rem;',
  h5: 'height: 16rem;',
  h25: 'height: 25%;',
  h50: 'height: 50%;',
  h75: 'height: 75%;',
  h100: 'height: 100%;',
  minH100: 'min-height: 100%;',
  vh25: 'height: 25vh;',
  vh50: 'height: 50vh;',
  vh75: 'height: 75vh;',
  vh100: 'height: 100vh;',
  minVh100: 'min-height: 100vh;',
  hAuto: 'height: auto;',
  hInherit: 'height: inherit;',
  dim: 'opacity: 1;-webkit-transition: opacity .15s ease-in;transition: opacity .15s ease-in;',
  dimActive: 'opacity: .8;-webkit-transition: opacity .15s ease-out;transition: opacity .15s ease-out;',
  hideChildChild: 'opacity: 0;-webkit-transition: opacity .15s ease-in;transition: opacity .15s ease-in;',
  grow: '-moz-osx-font-smoothing: grayscale;-webkit-backface-visibility: hidden;backface-visibility: hidden;-webkit-transform: translateZ( 0 );transform: translateZ( 0 );-webkit-transition: -webkit-transform .25s ease-out;transition: -webkit-transform .25s ease-out;transition: transform .25s ease-out;transition: transform .25s ease-out, -webkit-transform .25s ease-out;',
  growActive: '-webkit-transform: scale( .90 );transform: scale( .90 );',
  growLarge: '-moz-osx-font-smoothing: grayscale;-webkit-backface-visibility: hidden;backface-visibility: hidden;-webkit-transform: translateZ( 0 );transform: translateZ( 0 );-webkit-transition: -webkit-transform .25s ease-in-out;transition: -webkit-transform .25s ease-in-out;transition: transform .25s ease-in-out;transition: transform .25s ease-in-out, -webkit-transform .25s ease-in-out;',
  growLargeActive: '-webkit-transform: scale( .95 );transform: scale( .95 );',
  shadowHoverAfter: 'box-shadow: 0 0 8px 2px rgba( 0, 0, 0, .2 );opacity: 0;-webkit-transition: opacity .25s ease-in-out;transition: opacity .25s ease-in-out;',
  tracked: 'letter-spacing: .1em;',
  trackedTight: 'letter-spacing: -.05em;',
  trackedMega: 'letter-spacing: .25em;',
  lhSolid: 'line-height: 1;',
  lhTitle: 'line-height: 1.25;',
  lhCopy: 'line-height: 1.5;',
  link: 'text-decoration: none;-webkit-transition: color .15s ease-in;transition: color .15s ease-in;',
  linkLinkLinkVisited: '-webkit-transition: color .15s ease-in;transition: color .15s ease-in;',
  linkActive: '-webkit-transition: color .15s ease-in;transition: color .15s ease-in;',
  list: 'list-style-type: none;',
  mw100: 'max-width: 100%;',
  mw1: 'max-width: 1rem;',
  mw2: 'max-width: 2rem;',
  mw3: 'max-width: 4rem;',
  mw4: 'max-width: 8rem;',
  mw5: 'max-width: 16rem;',
  mw6: 'max-width: 32rem;',
  mw7: 'max-width: 48rem;',
  mw8: 'max-width: 64rem;',
  mw9: 'max-width: 96rem;',
  mwNone: 'max-width: none;',
  man1: 'margin: -.25rem;',
  man2: 'margin: -.5rem;',
  man3: 'margin: -1rem;',
  man4: 'margin: -2rem;',
  man5: 'margin: -4rem;',
  man6: 'margin: -8rem;',
  man7: 'margin: -16rem;',
  mln1: 'margin-left: -.25rem;',
  mln2: 'margin-left: -.5rem;',
  mln3: 'margin-left: -1rem;',
  mln4: 'margin-left: -2rem;',
  mln5: 'margin-left: -4rem;',
  mln6: 'margin-left: -8rem;',
  mln7: 'margin-left: -16rem;',
  mrn1: 'margin-right: -.25rem;',
  mrn2: 'margin-right: -.5rem;',
  mrn3: 'margin-right: -1rem;',
  mrn4: 'margin-right: -2rem;',
  mrn5: 'margin-right: -4rem;',
  mrn6: 'margin-right: -8rem;',
  mrn7: 'margin-right: -16rem;',
  mbn1: 'margin-bottom: -.25rem;',
  mbn2: 'margin-bottom: -.5rem;',
  mbn3: 'margin-bottom: -1rem;',
  mbn4: 'margin-bottom: -2rem;',
  mbn5: 'margin-bottom: -4rem;',
  mbn6: 'margin-bottom: -8rem;',
  mbn7: 'margin-bottom: -16rem;',
  mtn1: 'margin-top: -.25rem;',
  mtn2: 'margin-top: -.5rem;',
  mtn3: 'margin-top: -1rem;',
  mtn4: 'margin-top: -2rem;',
  mtn5: 'margin-top: -4rem;',
  mtn6: 'margin-top: -8rem;',
  mtn7: 'margin-top: -16rem;',
  mv1: 'margin-top: .25rem;margin-bottom: .25rem;',
  mv2: 'margin-top: .5rem;margin-bottom: .5rem;',
  mv3: 'margin-top: 1rem;margin-bottom: 1rem;',
  mv4: 'margin-top: 2rem;margin-bottom: 2rem;',
  mv5: 'margin-top: 4rem;margin-bottom: 4rem;',
  mv6: 'margin-top: 8rem;margin-bottom: 8rem;',
  mv7: 'margin-top: 16rem;margin-bottom: 16rem;',
  mhn1: 'margin-left: -.25rem;margin-right: -.25rem;',
  mhn2: 'margin-left: -.5rem;margin-right: -.5rem;',
  mhn3: 'margin-left: -1rem;margin-right: -1rem;',
  mhn4: 'margin-left: -2rem;margin-right: -2rem;',
  mhn5: 'margin-left: -4rem;margin-right: -4rem;',
  mhn6: 'margin-left: -8rem;margin-right: -8rem;',
  mhn7: 'margin-left: -16rem;margin-right: -16rem;',
  o100: 'opacity: 1;',
  o90: 'opacity: .9;',
  o80: 'opacity: .8;',
  o70: 'opacity: .7;',
  o60: 'opacity: .6;',
  o50: 'opacity: .5;',
  o40: 'opacity: .4;',
  o30: 'opacity: .3;',
  o20: 'opacity: .2;',
  o10: 'opacity: .1;',
  o05: 'opacity: .05;',
  o025: 'opacity: .025;',
  o0: 'opacity: 0;',
  outline: 'outline: 1px solid;',
  outlineTransparent: 'outline: 1px solid transparent;',
  outline0: 'outline: 0;',
  overflowVisible: 'overflow: visible;',
  overflowHidden: 'overflow: hidden;',
  overflowScroll: 'overflow: scroll;',
  overflowAuto: 'overflow: auto;',
  overflowXVisible: 'overflow-x: visible;',
  overflowXHidden: 'overflow-x: hidden;',
  overflowXScroll: 'overflow-x: scroll;',
  overflowXAuto: 'overflow-x: auto;',
  overflowYVisible: 'overflow-y: visible;',
  overflowYHidden: 'overflow-y: hidden;',
  overflowYScroll: 'overflow-y: scroll;',
  overflowYAuto: 'overflow-y: auto;',
  static: 'position: static;',
  relative: 'position: relative;',
  absolute: 'position: absolute;',
  fixed: 'position: fixed;',
  rotate45: '-webkit-transform: rotate( 45deg );transform: rotate( 45deg );',
  rotate90: '-webkit-transform: rotate( 90deg );transform: rotate( 90deg );',
  rotate135: '-webkit-transform: rotate( 135deg );transform: rotate( 135deg );',
  rotate180: '-webkit-transform: rotate( 180deg );transform: rotate( 180deg );',
  rotate225: '-webkit-transform: rotate( 225deg );transform: rotate( 225deg );',
  rotate270: '-webkit-transform: rotate( 270deg );transform: rotate( 270deg );',
  rotate315: '-webkit-transform: rotate( 315deg );transform: rotate( 315deg );',
  pa0: 'padding: 0;',
  pa1: 'padding: .25rem;',
  pa2: 'padding: .5rem;',
  pa3: 'padding: 1rem;',
  pa4: 'padding: 2rem;',
  pa5: 'padding: 4rem;',
  pa6: 'padding: 8rem;',
  pa7: 'padding: 16rem;',
  pl0: 'padding-left: 0;',
  pl1: 'padding-left: .25rem;',
  pl2: 'padding-left: .5rem;',
  pl3: 'padding-left: 1rem;',
  pl4: 'padding-left: 2rem;',
  pl5: 'padding-left: 4rem;',
  pl6: 'padding-left: 8rem;',
  pl7: 'padding-left: 16rem;',
  pr0: 'padding-right: 0;',
  pr1: 'padding-right: .25rem;',
  pr2: 'padding-right: .5rem;',
  pr3: 'padding-right: 1rem;',
  pr4: 'padding-right: 2rem;',
  pr5: 'padding-right: 4rem;',
  pr6: 'padding-right: 8rem;',
  pr7: 'padding-right: 16rem;',
  pb0: 'padding-bottom: 0;',
  pb1: 'padding-bottom: .25rem;',
  pb2: 'padding-bottom: .5rem;',
  pb3: 'padding-bottom: 1rem;',
  pb4: 'padding-bottom: 2rem;',
  pb5: 'padding-bottom: 4rem;',
  pb6: 'padding-bottom: 8rem;',
  pb7: 'padding-bottom: 16rem;',
  pt0: 'padding-top: 0;',
  pt1: 'padding-top: .25rem;',
  pt2: 'padding-top: .5rem;',
  pt3: 'padding-top: 1rem;',
  pt4: 'padding-top: 2rem;',
  pt5: 'padding-top: 4rem;',
  pt6: 'padding-top: 8rem;',
  pt7: 'padding-top: 16rem;',
  pv0: 'padding-top: 0;padding-bottom: 0;',
  pv1: 'padding-top: .25rem;padding-bottom: .25rem;',
  pv2: 'padding-top: .5rem;padding-bottom: .5rem;',
  pv3: 'padding-top: 1rem;padding-bottom: 1rem;',
  pv4: 'padding-top: 2rem;padding-bottom: 2rem;',
  pv5: 'padding-top: 4rem;padding-bottom: 4rem;',
  pv6: 'padding-top: 8rem;padding-bottom: 8rem;',
  pv7: 'padding-top: 16rem;padding-bottom: 16rem;',
  ph0: 'padding-left: 0;padding-right: 0;',
  ph1: 'padding-left: .25rem;padding-right: .25rem;',
  ph2: 'padding-left: .5rem;padding-right: .5rem;',
  ph3: 'padding-left: 1rem;padding-right: 1rem;',
  ph4: 'padding-left: 2rem;padding-right: 2rem;',
  ph5: 'padding-left: 4rem;padding-right: 4rem;',
  ph6: 'padding-left: 8rem;padding-right: 8rem;',
  ph7: 'padding-left: 16rem;padding-right: 16rem;',
  ma0: 'margin: 0;',
  ma1: 'margin: .25rem;',
  ma2: 'margin: .5rem;',
  ma3: 'margin: 1rem;',
  ma4: 'margin: 2rem;',
  ma5: 'margin: 4rem;',
  ma6: 'margin: 8rem;',
  ma7: 'margin: 16rem;',
  ml0: 'margin-left: 0;',
  ml1: 'margin-left: .25rem;',
  ml2: 'margin-left: .5rem;',
  ml3: 'margin-left: 1rem;',
  ml4: 'margin-left: 2rem;',
  ml5: 'margin-left: 4rem;',
  ml6: 'margin-left: 8rem;',
  ml7: 'margin-left: 16rem;',
  mr0: 'margin-right: 0;',
  mr1: 'margin-right: .25rem;',
  mr2: 'margin-right: .5rem;',
  mr3: 'margin-right: 1rem;',
  mr4: 'margin-right: 2rem;',
  mr5: 'margin-right: 4rem;',
  mr6: 'margin-right: 8rem;',
  mr7: 'margin-right: 16rem;',
  mb0: 'margin-bottom: 0;',
  mb1: 'margin-bottom: .25rem;',
  mb2: 'margin-bottom: .5rem;',
  mb3: 'margin-bottom: 1rem;',
  mb4: 'margin-bottom: 2rem;',
  mb5: 'margin-bottom: 4rem;',
  mb6: 'margin-bottom: 8rem;',
  mb7: 'margin-bottom: 16rem;',
  mt0: 'margin-top: 0;',
  mt1: 'margin-top: .25rem;',
  mt2: 'margin-top: .5rem;',
  mt3: 'margin-top: 1rem;',
  mt4: 'margin-top: 2rem;',
  mt5: 'margin-top: 4rem;',
  mt6: 'margin-top: 8rem;',
  mt7: 'margin-top: 16rem;',
  mv0: 'margin-top: 0;margin-bottom: 0;',
  mh0: 'margin-left: 0;margin-right: 0;',
  mh1: 'margin-left: .25rem;margin-right: .25rem;',
  mh2: 'margin-left: .5rem;margin-right: .5rem;',
  mh3: 'margin-left: 1rem;margin-right: 1rem;',
  mh4: 'margin-left: 2rem;margin-right: 2rem;',
  mh5: 'margin-left: 4rem;margin-right: 4rem;',
  mh6: 'margin-left: 8rem;margin-right: 8rem;',
  mh7: 'margin-left: 16rem;margin-right: 16rem;',
  collapse: 'border-collapse: collapse;border-spacing: 0;',
  stripedMoonGrayNthChildOdd: 'background-color: #ccc;',
  stripedLightGrayNthChildOdd: 'background-color: #f8f8f8;',
  stripedNearWhiteNthChildOdd: 'background-color: #f4f4f4;',
  tl: 'text-align: left;',
  tr: 'text-align: right;',
  tc: 'text-align: center;',
  strike: 'text-decoration: line-through;',
  underline: 'text-decoration: underline;',
  noUnderline: 'text-decoration: none;',
  ttc: 'text-transform: capitalize;',
  ttl: 'text-transform: lowercase;',
  ttu: 'text-transform: uppercase;',
  ttn: 'text-transform: none;',
  f6FHeadline: 'font-size: 6rem;',
  f5FSubheadline: 'font-size: 5rem;',
  f1: 'font-size: 3rem;',
  f2: 'font-size: 2.25rem;',
  f3: 'font-size: 1.5rem;',
  f4: 'font-size: 1.25rem;',
  f5: 'font-size: 1rem;',
  f6: 'font-size: .875rem;',
  measure: 'max-width: 30em;',
  measureWide: 'max-width: 34em;',
  measureNarrow: 'max-width: 20em;',
  indent: 'text-indent: 1em;margin-top: 0;margin-bottom: 0;',
  smallCaps: 'font-variant: small-caps;',
  truncate: 'white-space: nowrap;overflow: hidden;text-overflow: ellipsis;',
  overflowContainer: 'overflow-y: scroll;',
  center: 'margin-right: auto;margin-left: auto;',
  vBase: 'vertical-align: baseline;',
  vMid: 'vertical-align: middle;',
  vTop: 'vertical-align: top;',
  vBtm: 'vertical-align: bottom;',
  clip: 'position: fixed;position: absolute;clip: rect( 1px 1px 1px 1px );clip: rect( 1px, 1px, 1px, 1px );',
  wsNormal: 'white-space: normal;',
  nowrap: 'white-space: nowrap;',
  w1: 'width: 1rem;',
  w2: 'width: 2rem;',
  w3: 'width: 4rem;',
  w4: 'width: 8rem;',
  w5: 'width: 16rem;',
  w10: 'width: 10%;',
  w20: 'width: 20%;',
  w25: 'width: 25%;',
  w30: 'width: 30%;',
  w33: 'width: 33%;',
  w34: 'width: 34%;',
  w40: 'width: 40%;',
  w50: 'width: 50%;',
  w60: 'width: 60%;',
  w70: 'width: 70%;',
  w75: 'width: 75%;',
  w80: 'width: 80%;',
  w90: 'width: 90%;',
  w100: 'width: 100%;',
  wThird: 'width: calc( 100% / 3 );',
  wTwoThirds: 'width: calc( 100% / 1.5 );',
  wAuto: 'width: auto;',
  wordNormal: 'word-break: normal;',
  wordWrap: 'word-break: break-all;',
  wordNowrap: 'word-break: keep-all;',
  z0: 'z-index: 0;',
  z1: 'z-index: 1;',
  z2: 'z-index: 2;',
  z3: 'z-index: 3;',
  z4: 'z-index: 4;',
  z5: 'z-index: 5;',
  z999: 'z-index: 999;',
  z9999: 'z-index: 9999;',
  zMax: 'z-index: 2147483647;',
  zInherit: 'z-index: inherit;',
  zInitial: 'z-index: initial;',
  zUnset: 'z-index: unset;',
  flex: 'display: -webkit-box;display: -ms-flexbox;display: flex;',
  inlineFlex: 'display: -webkit-inline-box;display: -ms-inline-flexbox;display: inline-flex;',
  flexAuto: '-webkit-box-flex: 1;-ms-flex: 1 1 auto;flex: 1 1 auto;min-width: 0;min-height: 0;',
  flexNone: '-webkit-box-flex: 0;-ms-flex: none;flex: none;',
  flexColumn: '-webkit-box-orient: vertical;-webkit-box-direction: normal;-ms-flex-direction: column;flex-direction: column;',
  flexRow: '-webkit-box-orient: horizontal;-webkit-box-direction: normal;-ms-flex-direction: row;flex-direction: row;',
  flexWrap: '-ms-flex-wrap: wrap;flex-wrap: wrap;',
  itemsStart: '-webkit-box-align: start;-ms-flex-align: start;align-items: flex-start;',
  itemsEnd: '-webkit-box-align: end;-ms-flex-align: end;align-items: flex-end;',
  itemsCenter: '-webkit-box-align: center;-ms-flex-align: center;align-items: center;',
  itemsBaseline: '-webkit-box-align: baseline;-ms-flex-align: baseline;align-items: baseline;',
  itemsStretch: '-webkit-box-align: stretch;-ms-flex-align: stretch;align-items: stretch;',
  selfStart: '-ms-flex-item-align: start;align-self: flex-start;',
  selfEnd: '-ms-flex-item-align: end;align-self: flex-end;',
  selfCenter: '-ms-flex-item-align: center;-ms-grid-row-align: center;align-self: center;',
  selfBaseline: '-ms-flex-item-align: baseline;align-self: baseline;',
  selfStretch: '-ms-flex-item-align: stretch;-ms-grid-row-align: stretch;align-self: stretch;',
  justifyStart: '-webkit-box-pack: start;-ms-flex-pack: start;justify-content: flex-start;',
  justifyEnd: '-webkit-box-pack: end;-ms-flex-pack: end;justify-content: flex-end;',
  justifyCenter: '-webkit-box-pack: center;-ms-flex-pack: center;justify-content: center;',
  justifyBetween: '-webkit-box-pack: justify;-ms-flex-pack: justify;justify-content: space-between;',
  justifyAround: '-ms-flex-pack: distribute;justify-content: space-around;',
  contentStart: '-ms-flex-line-pack: start;align-content: flex-start;',
  contentEnd: '-ms-flex-line-pack: end;align-content: flex-end;',
  contentCenter: '-ms-flex-line-pack: center;align-content: center;',
  contentBetween: '-ms-flex-line-pack: justify;align-content: space-between;',
  contentAround: '-ms-flex-line-pack: distribute;align-content: space-around;',
  contentStretch: '-ms-flex-line-pack: stretch;align-content: stretch;',
  order0: '-webkit-box-ordinal-group: 1;-ms-flex-order: 0;order: 0;',
  order1: '-webkit-box-ordinal-group: 2;-ms-flex-order: 1;order: 1;',
  order2: '-webkit-box-ordinal-group: 3;-ms-flex-order: 2;order: 2;',
  order3: '-webkit-box-ordinal-group: 4;-ms-flex-order: 3;order: 3;',
  order4: '-webkit-box-ordinal-group: 5;-ms-flex-order: 4;order: 4;',
  order5: '-webkit-box-ordinal-group: 6;-ms-flex-order: 5;order: 5;',
  order6: '-webkit-box-ordinal-group: 7;-ms-flex-order: 6;order: 6;',
  order7: '-webkit-box-ordinal-group: 8;-ms-flex-order: 7;order: 7;',
  order8: '-webkit-box-ordinal-group: 9;-ms-flex-order: 8;order: 8;',
  orderLast: '-webkit-box-ordinal-group: 100000;-ms-flex-order: 99999;order: 99999;',
  flexGrow1: '-webkit-box-flex: 1;-ms-flex-positive: 1;flex-grow: 1;',
  flexGrow0: '-webkit-box-flex: 0;-ms-flex-positive: 0;flex-grow: 0;',
  flexShrink1: '-ms-flex-negative: 1;flex-shrink: 1;',
  flexShrink0: '-ms-flex-negative: 0;flex-shrink: 0;',
  root: '',
  black90: 'color: rgba( 0, 0, 0, .9 );',
  black80: 'color: rgba( 0, 0, 0, .8 );',
  black70: 'color: rgba( 0, 0, 0, .7 );',
  black60: 'color: rgba( 0, 0, 0, .6 );',
  black50: 'color: rgba( 0, 0, 0, .5 );',
  black40: 'color: rgba( 0, 0, 0, .4 );',
  black30: 'color: rgba( 0, 0, 0, .3 );',
  black20: 'color: rgba( 0, 0, 0, .2 );',
  black10: 'color: rgba( 0, 0, 0, .1 );',
  black05: 'color: rgba( 0, 0, 0, .05 );',
  white90: 'color: rgba( 255, 255, 255, .9 );',
  white80: 'color: rgba( 255, 255, 255, .8 );',
  white70: 'color: rgba( 255, 255, 255, .7 );',
  white60: 'color: rgba( 255, 255, 255, .6 );',
  white50: 'color: rgba( 255, 255, 255, .5 );',
  white40: 'color: rgba( 255, 255, 255, .4 );',
  white30: 'color: rgba( 255, 255, 255, .3 );',
  white20: 'color: rgba( 255, 255, 255, .2 );',
  white10: 'color: rgba( 255, 255, 255, .1 );',
  black: 'color: #000;',
  white: 'color: #fff;',
  whiteSecondary: 'color: #f8f8f8;',
  base: 'color: #232c3b;',
  baseSecondary: 'color: #171e27;',
  gray: 'color: #f4f5f9;',
  graySecondary: 'color: #e2e3e7;',
  darkGray: 'color: #63768d;',
  darkGraySecondary: 'color: #b0b6be;',
  blue: 'color: #4786ff;',
  blueSecondary: 'color: #386fda;',
  darkBlue: 'color: #344055;',
  darkBlueSecondary: 'color: #273040;',
  green: 'color: #59cd90;',
  greenSecondary: 'color: #409b6b;',
  orange: 'color: #fd9126;',
  orangeSecondary: 'color: #c97420;',
  red: 'color: #f0624d;',
  redSecondary: 'color: #c44c3a;',
  yellow: 'color: #fbc155;',
  yellowSecondary: 'color: #d2a043;',
  darkNavy: 'color: #171e27;',
  navy: 'color: #232c3b;',
  lightNavy: 'color: #344055;',
  lightGray: 'color: #f8f8f8;',
  tagGray: 'color: rgba( 255, 255, 255, .9 );',
  darkOrange: 'color: #c97420;',
  tagOrange: 'color: rgba( 255, 255, 255, .7 );',
  tagBlue: 'color: rgba( 255, 255, 255, .7 );',
  darkGreen: 'color: #409b6b;',
  turquoise: 'color: #409b6b;',
  tagTurquoise: 'color: rgba( 255, 255, 255, .7 );',
  darkRed: 'color: #c44c3a;',
  bgBlack90: 'background-color: rgba( 0, 0, 0, .9 );',
  bgBlack80: 'background-color: rgba( 0, 0, 0, .8 );',
  bgBlack70: 'background-color: rgba( 0, 0, 0, .7 );',
  bgBlack60: 'background-color: rgba( 0, 0, 0, .6 );',
  bgBlack50: 'background-color: rgba( 0, 0, 0, .5 );',
  bgBlack40: 'background-color: rgba( 0, 0, 0, .4 );',
  bgBlack30: 'background-color: rgba( 0, 0, 0, .3 );',
  bgBlack20: 'background-color: rgba( 0, 0, 0, .2 );',
  bgBlack10: 'background-color: rgba( 0, 0, 0, .1 );',
  bgBlack05: 'background-color: rgba( 0, 0, 0, .05 );',
  bgWhite90: 'background-color: rgba( 255, 255, 255, .9 );',
  bgWhite80: 'background-color: rgba( 255, 255, 255, .8 );',
  bgWhite70: 'background-color: rgba( 255, 255, 255, .7 );',
  bgWhite60: 'background-color: rgba( 255, 255, 255, .6 );',
  bgWhite50: 'background-color: rgba( 255, 255, 255, .5 );',
  bgWhite40: 'background-color: rgba( 255, 255, 255, .4 );',
  bgWhite30: 'background-color: rgba( 255, 255, 255, .3 );',
  bgWhite20: 'background-color: rgba( 255, 255, 255, .2 );',
  bgWhite10: 'background-color: rgba( 255, 255, 255, .1 );',
  bgBlack: 'background-color: #000;',
  bgWhite: 'background-color: #fff;',
  bgTransparent: 'background-color: transparent;',
  bgWhiteSecondary: 'background-color: #f8f8f8;',
  bgBase: 'background-color: #232c3b;',
  bgBaseSecondary: 'background-color: #171e27;',
  bgGray: 'background-color: #f4f5f9;',
  bgGraySecondary: 'background-color: #e2e3e7;',
  bgDarkGray: 'background-color: #63768d;',
  bgDarkGraySecondary: 'background-color: #b0b6be;',
  bgBlue: 'background-color: #4786ff;',
  bgBlueSecondary: 'background-color: #386fda;',
  bgDarkBlue: 'background-color: #344055;',
  bgDarkBlueSecondary: 'background-color: #273040;',
  bgGreen: 'background-color: #59cd90;',
  bgGreenSecondary: 'background-color: #409b6b;',
  bgOrange: 'background-color: #fd9126;',
  bgOrangeSecondary: 'background-color: #c97420;',
  bgRed: 'background-color: #f0624d;',
  bgRedSecondary: 'background-color: #c44c3a;',
  bgYellow: 'background-color: #fbc155;',
  bgYellowSecondary: 'background-color: #d2a043;',
  bgDarkNavy: 'background-color: #171e27;',
  bgNavy: 'background-color: #232c3b;',
  bgLightNavy: 'background-color: #344055;',
  bgLightGray: 'background-color: #f8f8f8;',
  bgTagGray: 'background-color: rgba( 255, 255, 255, .9 );',
  bgDarkOrange: 'background-color: #c97420;',
  bgTagOrange: 'background-color: rgba( 255, 255, 255, .7 );',
  bgTagBlue: 'background-color: rgba( 255, 255, 255, .7 );',
  bgDarkGreen: 'background-color: #409b6b;',
  bgTurquoise: 'background-color: #409b6b;',
  bgTagTurquoise: 'background-color: rgba( 255, 255, 255, .7 );',
  bgDarkRed: 'background-color: #c44c3a;',
  shadow1: 'box-shadow: 0 0 4px 0 rgba( 0, 0, 0, .2 );',
  shadow2: 'box-shadow: 0 0 8px 2px rgba( 0, 0, 0, .2 );',
  shadow3: 'box-shadow: 2px 2px 4px 2px rgba( 0, 0, 0, .2 );',
  shadow4: 'box-shadow: 2px 2px 8px 0 rgba( 0, 0, 0, .2 );',
  shadow5: 'box-shadow: 4px 4px 8px 0 rgba( 0, 0, 0, .2 );',
  bBlack: 'border-color: #000;',
  bWhite: 'border-color: #fff;',
  bWhite90: 'border-color: rgba( 255, 255, 255, .9 );',
  bWhite80: 'border-color: rgba( 255, 255, 255, .8 );',
  bWhite70: 'border-color: rgba( 255, 255, 255, .7 );',
  bWhite60: 'border-color: rgba( 255, 255, 255, .6 );',
  bWhite50: 'border-color: rgba( 255, 255, 255, .5 );',
  bWhite40: 'border-color: rgba( 255, 255, 255, .4 );',
  bWhite30: 'border-color: rgba( 255, 255, 255, .3 );',
  bWhite20: 'border-color: rgba( 255, 255, 255, .2 );',
  bWhite10: 'border-color: rgba( 255, 255, 255, .1 );',
  bWhite05: 'border-color: rgba( 255, 255, 255, .05 );',
  bWhite025: 'border-color: rgba( 255, 255, 255, .025 );',
  bWhite0125: 'border-color: rgba( 255, 255, 255, .0125 );',
  bBlack90: 'border-color: rgba( 0, 0, 0, .9 );',
  bBlack80: 'border-color: rgba( 0, 0, 0, .8 );',
  bBlack70: 'border-color: rgba( 0, 0, 0, .7 );',
  bBlack60: 'border-color: rgba( 0, 0, 0, .6 );',
  bBlack50: 'border-color: rgba( 0, 0, 0, .5 );',
  bBlack40: 'border-color: rgba( 0, 0, 0, .4 );',
  bBlack30: 'border-color: rgba( 0, 0, 0, .3 );',
  bBlack20: 'border-color: rgba( 0, 0, 0, .2 );',
  bBlack10: 'border-color: rgba( 0, 0, 0, .1 );',
  bBlack05: 'border-color: rgba( 0, 0, 0, .05 );',
  bBlack025: 'border-color: rgba( 0, 0, 0, .025 );',
  bBlack0125: 'border-color: rgba( 0, 0, 0, .0125 );',
  bTransparent: 'border-color: transparent;',
  bWhiteSecondary: 'border-color: #f8f8f8;',
  bBase: 'border-color: #232c3b;',
  bBaseSecondary: 'border-color: #171e27;',
  bGray: 'border-color: #f4f5f9;',
  bGraySecondary: 'border-color: #e2e3e7;',
  bDarkGray: 'border-color: #63768d;',
  bDarkGraySecondary: 'border-color: #b0b6be;',
  bBlue: 'border-color: #4786ff;',
  bBlueSecondary: 'border-color: #386fda;',
  bDarkBlue: 'border-color: #344055;',
  bDarkBlueSecondary: 'border-color: #273040;',
  bGreen: 'border-color: #59cd90;',
  bGreenSecondary: 'border-color: #409b6b;',
  bOrange: 'border-color: #fd9126;',
  bOrangeSecondary: 'border-color: #c97420;',
  bRed: 'border-color: #f0624d;',
  bRedSecondary: 'border-color: #c44c3a;',
  bYellow: 'border-color: #fbc155;',
  bYellowSecondary: 'border-color: #d2a043;',
  bDarkNavy: 'border-color: #171e27;',
  bNavy: 'border-color: #232c3b;',
  bLightNavy: 'border-color: #344055;',
  bLightGray: 'border-color: #f8f8f8;',
  bTagGray: 'border-color: rgba( 255, 255, 255, .9 );',
  bDarkOrange: 'border-color: #c97420;',
  bTagOrange: 'border-color: rgba( 255, 255, 255, .7 );',
  bTagBlue: 'border-color: rgba( 255, 255, 255, .7 );',
  bDarkGreen: 'border-color: #409b6b;',
  bTurquoise: 'border-color: #409b6b;',
  bTagTurquoise: 'border-color: rgba( 255, 255, 255, .7 );',
  bDarkRed: 'border-color: #c44c3a;' }
